export interface ListingSite {
  name: string;
  url: string;
  category:
    | "Launch Platforms"
    | "SaaS Review Sites"
    | "Startup Directories"
    | "Tech Media & Blogs"
    | "Communities & Social"
    | "India-Specific"
    | "Business Listings"
    | "Design & Dev";
}

export const listingSites: ListingSite[] = [
  // Business Listings
  { name: "Better Business Bureau", url: "https://www.bbb.org/", category: "Business Listings" },
  { name: "Bing Places", url: "https://www.bingplaces.com/", category: "Business Listings" },
  { name: "Foursquare", url: "https://foursquare.com/", category: "Business Listings" },
  { name: "Google Business Profile", url: "https://www.google.com/business/", category: "Business Listings" },
  { name: "Local.com", url: "https://www.local.com/", category: "Business Listings" },
  { name: "MerchantCircle", url: "https://www.merchantcircle.com/", category: "Business Listings" },
  { name: "Whitepages", url: "https://www.whitepages.com/", category: "Business Listings" },
  { name: "Yellow Pages", url: "https://www.yellowpages.com/", category: "Business Listings" },
  { name: "Yelp for Business", url: "https://business.yelp.com/", category: "Business Listings" },

  // Communities & Social
  { name: "Bootstrappers.io", url: "https://bootstrappers.io/", category: "Communities & Social" },
  { name: "CoFoundersLab", url: "https://cofounderslab.com/", category: "Communities & Social" },
  { name: "DEV Community", url: "https://dev.to/", category: "Communities & Social" },
  { name: "Digg", url: "https://digg.com/", category: "Communities & Social" },
  { name: "GrowthHackers", url: "https://growthhackers.com/", category: "Communities & Social" },
  { name: "Hacker News", url: "https://news.ycombinator.com/", category: "Communities & Social" },
  { name: "Indie Hackers", url: "https://www.indiehackers.com/", category: "Communities & Social" },
  { name: "LinkedIn", url: "https://www.linkedin.com/", category: "Communities & Social" },
  { name: "Lobsters", url: "https://lobste.rs/", category: "Communities & Social" },
  { name: "Medium", url: "https://medium.com/", category: "Communities & Social" },
  { name: "Online Geniuses", url: "https://onlinegeniuses.com/", category: "Communities & Social" },
  { name: "Pinterest", url: "https://www.pinterest.com/", category: "Communities & Social" },
  { name: "Quora", url: "https://www.quora.com/", category: "Communities & Social" },
  { name: "r/AlphaAndBetaUsers", url: "https://www.reddit.com/r/alphaandbetausers/", category: "Communities & Social" },
  { name: "r/Design_Critiques", url: "https://www.reddit.com/r/Design_Critiques/", category: "Communities & Social" },
  { name: "r/Entrepreneur", url: "https://www.reddit.com/r/Entrepreneur/", category: "Communities & Social" },
  { name: "r/EntrepreneurRideAlong", url: "https://www.reddit.com/r/EntrepreneurRideAlong/", category: "Communities & Social" },
  { name: "r/GrowMyBusiness", url: "https://www.reddit.com/r/growmybusiness/", category: "Communities & Social" },
  { name: "r/IMadeThis", url: "https://www.reddit.com/r/IMadeThis/", category: "Communities & Social" },
  { name: "r/IndieBiz", url: "https://www.reddit.com/r/indiebiz/", category: "Communities & Social" },
  { name: "r/javascript", url: "https://www.reddit.com/r/javascript/", category: "Communities & Social" },
  { name: "r/LadyBusiness", url: "https://www.reddit.com/r/ladybusiness/", category: "Communities & Social" },
  { name: "r/Python", url: "https://www.reddit.com/r/Python/", category: "Communities & Social" },
  { name: "r/RoastMyStartup", url: "https://www.reddit.com/r/roastmystartup/", category: "Communities & Social" },
  { name: "r/ShamelessPlug", url: "https://www.reddit.com/r/shamelessplug/", category: "Communities & Social" },
  { name: "r/SideProject", url: "https://www.reddit.com/r/SideProject/", category: "Communities & Social" },
  { name: "r/SmallBusiness", url: "https://www.reddit.com/r/smallbusiness/", category: "Communities & Social" },
  { name: "r/Startups", url: "https://www.reddit.com/r/startups/", category: "Communities & Social" },
  { name: "r/webdev", url: "https://www.reddit.com/r/webdev/", category: "Communities & Social" },
  { name: "SaaS Breakthrough Community (Facebook)", url: "https://www.facebook.com/groups/saasbreakthrough/", category: "Communities & Social" },
  { name: "SaaS Products & Marketing (Facebook)", url: "https://www.facebook.com/groups/saasproductsandmarketing/", category: "Communities & Social" },
  { name: "Slashdot", url: "https://slashdot.org/", category: "Communities & Social" },
  { name: "The Hive Index", url: "https://thehiveindex.com/", category: "Communities & Social" },
  { name: "Tumblr", url: "https://www.tumblr.com/", category: "Communities & Social" },
  { name: "Unita", url: "https://www.unita.co/", category: "Communities & Social" },
  { name: "X (Twitter)", url: "https://x.com/", category: "Communities & Social" },
  { name: "YC Startup School", url: "https://www.startupschool.org/", category: "Communities & Social" },
  { name: "YouTube", url: "https://www.youtube.com/", category: "Communities & Social" },

  // Design & Dev
  { name: "Behance", url: "https://www.behance.net/", category: "Design & Dev" },
  { name: "Changelog", url: "https://changelog.com/", category: "Design & Dev" },
  { name: "Devpost", url: "https://devpost.com/", category: "Design & Dev" },
  { name: "Dribbble", url: "https://dribbble.com/", category: "Design & Dev" },
  { name: "Land-book", url: "https://land-book.com/", category: "Design & Dev" },
  { name: "Landingfolio", url: "https://www.landingfolio.com/", category: "Design & Dev" },
  { name: "NoCode.tech", url: "https://www.nocode.tech/", category: "Design & Dev" },
  { name: "SourceForge", url: "https://sourceforge.net/", category: "Design & Dev" },
  { name: "StackShare", url: "https://stackshare.io/", category: "Design & Dev" },
  { name: "UpLabs", url: "https://www.uplabs.com/", category: "Design & Dev" },
  { name: "Web Designer News", url: "https://webdesignernews.com/", category: "Design & Dev" },
  { name: "Web Tools Weekly", url: "https://webtoolsweekly.com/", category: "Design & Dev" },
  { name: "Webdesign Inspiration", url: "https://www.webdesign-inspiration.com/", category: "Design & Dev" },

  // India-Specific
  { name: "Inc42", url: "https://inc42.com/", category: "India-Specific" },
  { name: "IndiaMART", url: "https://seller.indiamart.com/", category: "India-Specific" },
  { name: "Indian Yellow Pages", url: "https://www.indianyellowpages.com/", category: "India-Specific" },
  { name: "Justdial", url: "https://www.justdial.com/Free-Listing", category: "India-Specific" },
  { name: "Karo Startup", url: "https://karostartup.com/", category: "India-Specific" },
  { name: "LetsVenture", url: "https://letsventure.com/", category: "India-Specific" },
  { name: "NextBigWhat", url: "https://nextbigwhat.com/", category: "India-Specific" },
  { name: "Oye Startups", url: "https://oyestartups.com/", category: "India-Specific" },
  { name: "Sulekha", url: "https://www.sulekha.com/", category: "India-Specific" },
  { name: "The Indianpreneur", url: "https://theindianpreneur.com/", category: "India-Specific" },
  { name: "TradeIndia", url: "https://www.tradeindia.com/", category: "India-Specific" },
  { name: "Women Entrepreneurs Portal", url: "https://wep.gov.in/", category: "India-Specific" },
  { name: "YourStory", url: "https://yourstory.com/", category: "India-Specific" },

  // Launch Platforms
  { name: "10words", url: "https://10words.io/", category: "Launch Platforms" },
  { name: "AppSumo", url: "https://appsumo.com/", category: "Launch Platforms" },
  { name: "Betabound", url: "https://www.betabound.com/", category: "Launch Platforms" },
  { name: "BetaList", url: "https://betalist.com/", category: "Launch Platforms" },
  { name: "BetaPage", url: "https://betapage.co/", category: "Launch Platforms" },
  { name: "Get Worm", url: "https://getworm.com/", category: "Launch Platforms" },
  { name: "Launching Next", url: "https://www.launchingnext.com/", category: "Launch Platforms" },
  { name: "Postmake", url: "https://postmake.io/", category: "Launch Platforms" },
  { name: "Product Hunt", url: "https://www.producthunt.com/", category: "Launch Platforms" },
  { name: "Spectacle", url: "https://spectacle.is/", category: "Launch Platforms" },
  { name: "StartupBase", url: "https://startupbase.io/", category: "Launch Platforms" },

  // SaaS Review Sites
  { name: "AlternativeTo", url: "https://alternativeto.net/", category: "SaaS Review Sites" },
  { name: "AppAgg", url: "https://appagg.com/", category: "SaaS Review Sites" },
  { name: "Business-Software.com", url: "https://www.business-software.com/", category: "SaaS Review Sites" },
  { name: "CabinetM", url: "https://www.cabinetm.com/", category: "SaaS Review Sites" },
  { name: "Capterra", url: "https://www.capterra.com/", category: "SaaS Review Sites" },
  { name: "Clutch", url: "https://clutch.co/", category: "SaaS Review Sites" },
  { name: "ComparaSoftware", url: "https://www.comparasoftware.com/", category: "SaaS Review Sites" },
  { name: "CrowdReviews", url: "https://www.crowdreviews.com/", category: "SaaS Review Sites" },
  { name: "Crozdesk", url: "https://crozdesk.com/", category: "SaaS Review Sites" },
  { name: "Cuspera", url: "https://www.cuspera.com/", category: "SaaS Review Sites" },
  { name: "DiscoverCloud", url: "https://www.discovercloud.com/", category: "SaaS Review Sites" },
  { name: "FeaturedCustomers", url: "https://www.featuredcustomers.com/", category: "SaaS Review Sites" },
  { name: "FinancesOnline", url: "https://financesonline.com/", category: "SaaS Review Sites" },
  { name: "G2", url: "https://www.g2.com/", category: "SaaS Review Sites" },
  { name: "GetApp", url: "https://www.getapp.com/", category: "SaaS Review Sites" },
  { name: "How To Buy SaaS", url: "https://www.howtobuysaas.com/", category: "SaaS Review Sites" },
  { name: "Remote Tools", url: "https://www.remote.tools/", category: "SaaS Review Sites" },
  { name: "SaaS Directory", url: "https://saasdirectory.com/", category: "SaaS Review Sites" },
  { name: "SaaSGenius", url: "https://www.saasgenius.com/", category: "SaaS Review Sites" },
  { name: "SaaSHub", url: "https://www.saashub.com/", category: "SaaS Review Sites" },
  { name: "SaaSworthy", url: "https://www.saasworthy.com/", category: "SaaS Review Sites" },
  { name: "Serchen", url: "https://www.serchen.com/", category: "SaaS Review Sites" },
  { name: "Sitejabber", url: "https://www.sitejabber.com/", category: "SaaS Review Sites" },
  { name: "Slant", url: "https://www.slant.co/", category: "SaaS Review Sites" },
  { name: "Software Advice", url: "https://www.softwareadvice.com/", category: "SaaS Review Sites" },
  { name: "SoftwareSuggest", url: "https://www.softwaresuggest.com/", category: "SaaS Review Sites" },
  { name: "SoftwareWorld", url: "https://www.softwareworld.co/", category: "SaaS Review Sites" },
  { name: "Trustpilot", url: "https://www.trustpilot.com/", category: "SaaS Review Sites" },
  { name: "TrustRadius", url: "https://www.trustradius.com/", category: "SaaS Review Sites" },

  // Startup Directories
  { name: "Alpha Digits", url: "https://alphadigits.com/", category: "Startup Directories" },
  { name: "American Startups", url: "https://americanstartups.com/", category: "Startup Directories" },
  { name: "AngelList (Wellfound)", url: "https://wellfound.com/", category: "Startup Directories" },
  { name: "Crazy About Startups", url: "https://crazyaboutstartups.com/", category: "Startup Directories" },
  { name: "Crunchbase", url: "https://www.crunchbase.com/", category: "Startup Directories" },
  { name: "EU-Startups", url: "https://www.eu-startups.com/", category: "Startup Directories" },
  { name: "F6S", url: "https://www.f6s.com/", category: "Startup Directories" },
  { name: "Feedough", url: "https://www.feedough.com/", category: "Startup Directories" },
  { name: "Growth Junkie", url: "https://growthjunkie.com/", category: "Startup Directories" },
  { name: "Gust", url: "https://gust.com/", category: "Startup Directories" },
  { name: "Index.co", url: "https://index.co/", category: "Startup Directories" },
  { name: "InnMind", url: "https://innmind.com/", category: "Startup Directories" },
  { name: "KillerStartups", url: "https://www.killerstartups.com/", category: "Startup Directories" },
  { name: "MAGNiTT", url: "https://magnitt.com/", category: "Startup Directories" },
  { name: "MicroStartups", url: "https://www.microstartups.co/", category: "Startup Directories" },
  { name: "PitchBook", url: "https://pitchbook.com/", category: "Startup Directories" },
  { name: "Promote Project", url: "https://www.promoteproject.com/", category: "Startup Directories" },
  { name: "Romanian Startups", url: "https://www.romanianstartups.com/", category: "Startup Directories" },
  { name: "Side Projectors", url: "https://www.sideprojectors.com/", category: "Startup Directories" },
  { name: "Startup Buffer", url: "https://startupbuffer.com/", category: "Startup Directories" },
  { name: "Startup Collections", url: "https://startupcollections.com/", category: "Startup Directories" },
  { name: "Startup Inspire", url: "https://startupinspire.com/", category: "Startup Directories" },
  { name: "Startup Ranking", url: "https://www.startupranking.com/", category: "Startup Directories" },
  { name: "Startup Resources", url: "https://startupresources.io/", category: "Startup Directories" },
  { name: "Startup Savant", url: "https://startupsavant.com/", category: "Startup Directories" },
  { name: "Startup Stash", url: "https://startupstash.com/", category: "Startup Directories" },
  { name: "Startup Tracker", url: "https://startuptracker.io/", category: "Startup Directories" },
  { name: "Startup World", url: "https://www.startupworld.com/", category: "Startup Directories" },
  { name: "Startups of London", url: "https://startupsoflondon.com/", category: "Startup Directories" },
  { name: "Startupxplore", url: "https://startupxplore.com/", category: "Startup Directories" },
  { name: "Tracxn", url: "https://tracxn.com/", category: "Startup Directories" },
  { name: "Valuer", url: "https://www.valuer.ai/", category: "Startup Directories" },
  { name: "VentureRadar", url: "https://www.ventureradar.com/", category: "Startup Directories" },
  { name: "YouNoodle", url: "https://www.younoodle.com/", category: "Startup Directories" },

  // Tech Media & Blogs
  { name: "Addictive Tips", url: "https://www.addictivetips.com/", category: "Tech Media & Blogs" },
  { name: "Alltop", url: "https://alltop.com/", category: "Tech Media & Blogs" },
  { name: "AllTopStartups", url: "https://alltopstartups.com/", category: "Tech Media & Blogs" },
  { name: "American Inno", url: "https://www.americaninno.com/", category: "Tech Media & Blogs" },
  { name: "Android Apps Review", url: "https://www.androidappsreview.com/", category: "Tech Media & Blogs" },
  { name: "Android Authority", url: "https://www.androidauthority.com/", category: "Tech Media & Blogs" },
  { name: "Android Central", url: "https://www.androidcentral.com/", category: "Tech Media & Blogs" },
  { name: "AndroidGuys", url: "https://www.androidguys.com/", category: "Tech Media & Blogs" },
  { name: "Android Police", url: "https://www.androidpolice.com/", category: "Tech Media & Blogs" },
  { name: "App Rater", url: "https://apprater.net/", category: "Tech Media & Blogs" },
  { name: "AppleInsider", url: "https://appleinsider.com/", category: "Tech Media & Blogs" },
  { name: "Apps400", url: "https://apps400.com/", category: "Tech Media & Blogs" },
  { name: "AppSpy", url: "https://www.appspy.com/", category: "Tech Media & Blogs" },
  { name: "ArcticStartup", url: "https://arcticstartup.com/", category: "Tech Media & Blogs" },
  { name: "Ars Technica", url: "https://arstechnica.com/", category: "Tech Media & Blogs" },
  { name: "BetaKit", url: "https://betakit.com/", category: "Tech Media & Blogs" },
  { name: "Boing Boing", url: "https://boingboing.net/", category: "Tech Media & Blogs" },
  { name: "Built In", url: "https://builtin.com/", category: "Tech Media & Blogs" },
  { name: "Business Insider", url: "https://www.businessinsider.com/", category: "Tech Media & Blogs" },
  { name: "Business2Community", url: "https://www.business2community.com/", category: "Tech Media & Blogs" },
  { name: "CNET", url: "https://www.cnet.com/", category: "Tech Media & Blogs" },
  { name: "Digital Trends", url: "https://www.digitaltrends.com/", category: "Tech Media & Blogs" },
  { name: "Engadget", url: "https://www.engadget.com/", category: "Tech Media & Blogs" },
  { name: "Fast Company", url: "https://www.fastcompany.com/", category: "Tech Media & Blogs" },
  { name: "Fintech News Singapore", url: "https://fintechnews.sg/", category: "Tech Media & Blogs" },
  { name: "Future of SaaS", url: "https://www.futureofsaas.io/", category: "Tech Media & Blogs" },
  { name: "GeekWire", url: "https://www.geekwire.com/", category: "Tech Media & Blogs" },
  { name: "HackerNoon", url: "https://hackernoon.com/", category: "Tech Media & Blogs" },
  { name: "InfoWorld", url: "https://www.infoworld.com/", category: "Tech Media & Blogs" },
  { name: "Lifehack", url: "https://www.lifehack.org/", category: "Tech Media & Blogs" },
  { name: "MakeUseOf", url: "https://www.makeuseof.com/", category: "Tech Media & Blogs" },
  { name: "Mashable", url: "https://mashable.com/", category: "Tech Media & Blogs" },
  { name: "PCMag", url: "https://www.pcmag.com/", category: "Tech Media & Blogs" },
  { name: "Pocket-lint", url: "https://www.pocket-lint.com/", category: "Tech Media & Blogs" },
  { name: "Project Hatch", url: "https://www.projecthatch.co/", category: "Tech Media & Blogs" },
  { name: "ReadWrite", url: "https://readwrite.com/", category: "Tech Media & Blogs" },
  { name: "SiliconANGLE", url: "https://siliconangle.com/", category: "Tech Media & Blogs" },
  { name: "Springwise", url: "https://www.springwise.com/", category: "Tech Media & Blogs" },
  { name: "Starter Story", url: "https://www.starterstory.com/", category: "Tech Media & Blogs" },
  { name: "StartupBeat", url: "https://startupbeat.com/", category: "Tech Media & Blogs" },
  { name: "Startup Guys", url: "https://startupguys.net/", category: "Tech Media & Blogs" },
  { name: "Startups.co.uk", url: "https://startups.co.uk/", category: "Tech Media & Blogs" },
  { name: "SuperbCrew", url: "https://www.superbcrew.com/", category: "Tech Media & Blogs" },
  { name: "Tapscape", url: "https://www.tapscape.com/", category: "Tech Media & Blogs" },
  { name: "Tech in Asia", url: "https://www.techinasia.com/", category: "Tech Media & Blogs" },
  { name: "Tech.co", url: "https://tech.co/", category: "Tech Media & Blogs" },
  { name: "Tech.eu", url: "https://tech.eu/", category: "Tech Media & Blogs" },
  { name: "TechCrunch", url: "https://techcrunch.com/", category: "Tech Media & Blogs" },
  { name: "Techdirt", url: "https://www.techdirt.com/", category: "Tech Media & Blogs" },
  { name: "TechPluto", url: "https://www.techpluto.com/", category: "Tech Media & Blogs" },
  { name: "The Next Web", url: "https://thenextweb.com/", category: "Tech Media & Blogs" },
  { name: "The Verge", url: "https://www.theverge.com/", category: "Tech Media & Blogs" },
  { name: "VentureBeat", url: "https://venturebeat.com/", category: "Tech Media & Blogs" },
  { name: "Webrazzi", url: "https://webrazzi.com/", category: "Tech Media & Blogs" },
  { name: "Young Upstarts", url: "https://www.youngupstarts.com/", category: "Tech Media & Blogs" },
  { name: "ZDNET", url: "https://www.zdnet.com/", category: "Tech Media & Blogs" },
];

export const listingSiteCount = listingSites.length;
